# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.__version__
np.show_config()

openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
a=[1,2,3,4,5,6,7,8]
arr2=np.array(a)
arr2

array([1, 2, 3, 4, 5, 6, 7, 8])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

In [ ]:
arr3=np.zeros(9)
arr3

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr4=np.size(arr3)
arr4


9

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
arr5=np.info(arr3)

class:  ndarray
shape:  (9,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x5b0577721260
byteorder:  little
byteswap:  False
type: float64


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr6=np.zeros(12)
arr6[6]=1
arr6

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr7=np.arange(20,59)
arr7

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr8=-np.sort(-arr7)
arr8

array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr9=np.arange(12,21).reshape(3,3)
arr9

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
ber=[3, 7, 0, 0, 9, 0]
arr10=np.nonzero(ber)
arr10

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr11=np.random.randn(2,2,2)
arr11

array([[[ 0.63854954,  0.49666037],
        [ 0.12294548, -0.21717805]],

       [[ 0.76412345, -0.19233382],
        [ 1.77886096,  1.03577102]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr12=np.random.randn(9,9)
print(np.min(arr12))
print(np.max(arr12))

-3.004686009866401
3.253319017718441


#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr14 = np.random.rand(6, 3)
arr14_1 = np.random.rand(3, 4)
data14 = np.dot(arr14, arr14_1)
print(data14)

[[0.76849373 0.6297677  0.98960241 1.66590149]
 [0.12663614 0.05973176 0.1293816  0.21079842]
 [0.41630753 0.31279064 0.57245926 0.90734262]
 [0.21673565 0.33489078 0.22596349 0.56018568]
 [0.36436143 0.42496002 0.70146905 1.07991707]
 [0.28378168 0.53757105 0.49436576 0.97386968]]


#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
10

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)
c = a + b
d = a * b
e = a / b

print(c)
print(d)
print(e)

[False False]
[False False]
[ True  True]
[ True  True]
[5 7]
[ 4 10]
[0.25 0.4 ]


#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan qiymatga olib keladi. sababi 0 ni 0ga bo'lib bo'lmaydi

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
a1=np.array([1,2,3,4,5,7,9])
a2=([1,3,5,9,10,15,])
arr18=np.intersect1d(a1,a2)
arr18

array([1, 3, 5, 9])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr19=np.arange(2.4,3.2,0.1)
data19=np.floor(arr19)
print("Butun: ",data19)


Butun:  [2. 2. 2. 2. 2. 2. 3. 3. 3.]


#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr20=np.array([[0, 1, 2], [1, 0, 2], [2, 1, 0]])
arr20

array([[0, 1, 2],
       [1, 0, 2],
       [2, 1, 0]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr21=np.random.rand(10)
data21=np.sort(arr21)
data21

array([0.03085088, 0.03507732, 0.09862694, 0.17710364, 0.36105875,
       0.47746068, 0.72017776, 0.82757075, 0.86107439, 0.97892858])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A=np.random.rand(5)
B=np.random.rand(5)
print(np.array_equal(A, B))
print(np.allclose(A, B))

False
False


#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
arr23 = np.random.rand(6, 3)
arr23_1 = np.random.rand(3, 4)
data23 = np.dot(arr23, arr23_1)
print(data23)

[[0.62246789 0.32762183 0.09646394 0.17745914]
 [0.7251213  0.67474176 0.61162889 0.11941009]
 [0.92677721 0.78269686 0.39465989 0.32098696]
 [0.86584061 0.9491394  0.28481445 0.49685717]
 [0.74718578 0.64216441 0.06512469 0.41201746]
 [0.51654096 0.6020625  0.54577278 0.10456119]]


#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr24=np.random.rand(5)
maks24=np.argmax(arr24)
maks24=0



arr24




array([0.01090621, 0.14022205, 0.58487224, 0.84451063, 0.94300623])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
import numpy as np
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')

print("Yesterday's date:", yesterday)
print("Today's date:", today)
print("Tomorrow's date:", tomorrow)

Yesterday's date: 2023-12-11
Today's date: 2023-12-12
Tomorrow's date: 2023-12-13


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
import numpy as np
jan_2016 = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
jan_2016 = jan_2016[jan_2016.astype('datetime64[M]') == np.datetime64('2016-01')]

print("All dates in January 2016:")
print(jan_2016)

All dates in January 2016:
['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
arr19=np.arange(2.4,3.2,0.1)
data19=np.floor(arr19)
print("Butun: ",data19)

Butun:  [2. 2. 2. 2. 2. 2. 3. 3. 3.]


#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
arr28=np.array([1,2,3,4,5,6])
summa=np.add.reduce(arr28)
summa

21

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
berilgan = [1, 2, 3, 4, 5]
yangi = []

for num in berilgan:
    yangi.append(num)
    yangi.extend([0, 0, 0])
yangi = yangi[:-3]

print(yangi)

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
b = [a[i:i+4]
for i in range(len(a)-3)]
#chat GPT dan yordam oldim!!!
print(b)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
arr31=np.array([1,2,4,5,7,9,1,2,8,4,3,1,4,2,9,7,3,1,5])
data31=np.bincount(arr31)
data31

array([0, 4, 3, 2, 3, 2, 0, 2, 1, 2])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [ ]:
#Rahmat